
service: calcutta-league-management-api

package:
  individually: true

plugins:
  - serverless-bundle

custom:
  stage: ${opt:stage, self:provider.stage}
  profile:
    prod: burke03
    dev: dev

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 15
  region: us-east-1
  stage: dev
  environment:
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST:
      Fn::GetAtt: [ CalcuttaDB, Endpoint.Address ]
    DB_PORT:
      Fn::GetAtt: [ CalcuttaDB, Endpoint.Port ]
  vpc:
    securityGroupIds:
      - Fn::ImportValue: calcutta-lambdaSG-${self:custom.stage}
    subnetIds:
      - Fn::ImportValue: calcutta-lambda-subnet1-${self:custom.stage}
      - Fn::ImportValue: calcutta-lambda-subnet2-${self:custom.stage}
      - Fn::ImportValue: calcutta-lambda-subnet3-${self:custom.stage}

functions:
  createLeague:
    handler: functions/createLeague.createLeague
    events:
      - http:
          path: createLeague
          method: post
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: '*'
            headers:
              - Content-Type
              - x-cognito-token

  joinLeague:
    handler: functions/joinLeague.joinLeague
    events:
      - http:
          path: joinLeague
          method: post
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: '*'
            headers:
              - Content-Type
              - x-cognito-token

  # updateLeagueSettings:
  #   handler: functions/leagueSettings.updateLeagueSettings
  #   events:
  #     - http:
  #         path: updateLeagueSettings
  #         method: post
  #         integration: lambda
  #         authorizer:
  #           type: COGNITO_USER_POOLS
  #           authorizerId:
  #             Ref: ApiGatewayAuthorizer
  #         cors:
  #           origin: '*'
  #           headers:
  #             - Content-Type
  #             - x-cognito-token

resources:
  - ${file(../common/resources/api-gateway-authorizer.yml)}