language: node_js
node_js:
  - stable

branches:
  only:
    - master
    - develop
notifications:
  email:
    on_failure: change
    on_success: change

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules

  install:
    - npm install -g serverless
    - travis_retry npm install

  script:
    - serverless deploy -s ${STAGE_NAME}

environments:
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}

  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEV}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEV}

jobs:
  include:
    # non-master branches deploys to dev
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy to the dev account"
      if: type = push AND NOT branch = master
      env:
        - STAGE_NAME="dev"
        - *DEVELOPMENT_ENV

    # master branch deploys to prod
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy to the prod account"
      if: type = push AND branch = master
      env:
        - STAGE_NAME=prod
        - *PRODUCTION_ENV