language: node_js
node_js:
- stable
branches:
  only:
  - master
  - develop
notifications:
  email:
    on_failure: always
    on_success: always
deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules
  install:
    - npm install -g serverless
    - travis_retry npm install
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -
  script:
    - cd ${SERVICE_PATH}
    - serverless deploy -s ${STAGE_NAME}
    - cd -
env:
  prod:
  - &5
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}
  dev:
  - &4
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEV}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEV}
    - secure: E0jPgpjh5wnMuN+NWmUNOe5dkyqkKdtoeku+niT39EVtk5Z5n7PXaJzoBFlx1StzWKvYT24iOn5zvp5ywI71SK0ejEQonW61XDQS8lP7Zz8lQ0/98qWMHc8ZL125O7QLwfwuu4qI2QJZf8fAEsIJR0Wzduj5fu+Jonf/AGPIEb6yM44GtGM9T9RWpJRat3Jy3G4dPuOrSsIIxNUggJsFFl35ThulP2i6uANlIiNSxMs6EqS2i93amCUHOgyLhI5l5NT/VZmMsVPZr79Y3CTibag4fJ2Pxr2QJFLsX7wW8YRZZaPOe791B+nstz8IjEX3dV8xehFu1T90H3RsOHn/O7v5/du8BrY4hYQE0rACMIZ68U7uj1s08rKTcvDPNhDsmMrEPE7pdPKhJWjIdvLPKauzDzkIdDnE/m/jbHVsaIg6bQvr2kEGOSZ37SJcddqo8/LNOLtwp4PE4Hmo87TKkdB+lDNUAy+ObzUmNftkUeVtWHzbSOUyyplnZTyFVY/FvYRgMCAF2mT8JYTu2L2V/HsMNv+CL49ETQpGSSqagDSjYbAS17nIVAhvFq+uLSs4oF54+IeJN+QNq6uK7paFSQ2xVjJYuyPb2yiyv56LqMCnZKHps3TdPm7FNixkJqMXDpexMHx1w7FyaQKuxuu+6hGC1lS41kTUjh0wAb6PVwA=
    - secure: XB5t8dSDXp7hZO18qX3WWDJFd8YS3ZBEcOLLyZWYWnWpeP6Ey3QOsfxKy8uLsGSAt0k7Ld/hdl5KLk1Cyg14UOVfTh3xbSgaTiBJfQpcQLL2rCQN/rErnsMVPCq/LHVrM6FmamCRlYDr8cKmLUdeCR5C5tg0fmRvds9Q3rZzwBibby/BGMPlX+bZBh92jBtw7Y7CfdmrhH/q/Yww4kaLJYpaGx5nrJYgDDsmvIg8+8SqPqeuYR8/rGqY/FhwhHrHCGgZ4S08sEQjv9HAw5K2uybXSqr+uS41wPeRag/V3+XmkiUl/DX7wnkGGtNKscI3No1gpE1Sz417L5dUVpgn6NoEfdPChDVdOd7ngjm5E/14G2zqo0bBBkHeO0tJYAKIFH1zyEZAKPpwYXGs0Uxzz9mBlC8RE86/3/zebj3lg3I4/JtYsYCcz7+i9+HJuOGTfzBWwhHc/YcZ87GpSNV2v1BqAf2Au1DbGxq8c6rBdwPArHDqcF9s9FzF9dwj5mi3VnSdXLSJAcQYxLQOmvxxxIrBLllW5Pyol4A7kfmGSGaP6yGSzZrzAAxRYGrLg5Yf1CexhawgsF//qOsFAq+dKtG4LfGwfFWlCFsz/LvFuDYVqehsv6wkWbZ6RCyPTbkGAECDWdrkLLixK/nJNmYtPYMlvrSGzItFq9YaUES0Lms=
    - secure: wB0HpDQUNvRfRA4y7A1m7Y+BfTwcrDgxyhPyex0iBUnRQczNYtv2hhCbek4HHCFfcI8n5YHiwjF5dKHCBQZNE1zUdzoj+c0t34MYifAHZCMtmgUpeu2WaiEEd1NfegX9mBK2i1FdCfSD1TmLAIXF7n5zxbuGL06q8Gp6nRw2ykSw4Coc2fbvxCnMMZD+fvTPaaeoykVAEfVjUweQDEDg804eLuJI/3jqbqDBpH+3HMRCPt/Njj/aNO/ZZOVxclDGm4JNB4w3J9I7zyU9aQwophrlqFxlTKIb1rp/ELQEyCLrH4YqgIXdrEGntfzMRyVojXSLFPTHm0rSNV8mCd1spX86tUcJRB2Bnc4460ITa5AQLB/QRNvOTashNNpF5MtWS4vpihd9WqcC+gHdTX+jqi9JYmHTxTmQ4/+YEjz78sh5Xwt5Kom9Msb+RLsmEsNyYIiml2JutQ15ENSAeAS8m4pgQT6jWyyFOok12oRQz+5aawqrm41BjtsJGcnoChKQkEtJoPVyQokP4Ny6OqTYaqq+/77hJoa3i91B8dBp6jz/iuSakEn82UEGHFCYFpJC7K7tMB3MyNRFmz+6I9sv2YZLOwi2toEkrA6tLVP9bs/cJbZBovZ9lbkD2CmbrQjJyAa/6ir5WXJ4YIc6GftOqhf5ddy1PJsgR03snNz7Mpo=
    - secure: Vv0XDGsX7pGl5BgbicWOYvOT0dpyc74ArZQd7zLclpZc+zimlZjKDVmKflYHWgNb4Cjy1xq1EVugiPyV+H3tDV8aJbdH5x8V2a6StUEduMwyMsZFI7Ey56lnlFckSjD41mtb2gZbUXd0UBmmFtIAbhSUpqRIph0GKOz+UWQks7rL3ie4vJF6MxkPgkM8lA2Tvtbdm/etVzNYWCn6mrzoRjrmWy9a0cX5U6zatVTM5zZ5POypmdZK2fNUku5am/Sqlf6IHIjMMawZZH4ny2i0299lsFBeY4wQ7ZteFKjohoVOPRgu/3AFxYSD/EpjVsRpP6Ljsx7nayzj68ZOq6Gy1dWOXZNMy82VAejsBl2HUZFt9uICuK/lElIZbLyr8wHQ6FGKEqdyKHhUl/mqP4QEVS9NAHZ9E2FK6JLNnNWTaGhhWf4Hgn20YsB2hA3kfDvGRQ5eR5gkxg2PjIkBlNyTi66q32sJ3Em2Ci+nc0XglKkaxxObVIfv1HPVXSOAxFUXxb99f5Cd/2ZS7iSWas9/7TBdSDWvxfXB/FaXxlgfxJTRjmOUhTig9Rh9l/a7diGBIgP2JsQBS8K8Qo3cJqEptLQMpfFBgen4p4DfhH3k18xenNce0PPdpAD7D4M2yN3OfkGgaSym9QZR9XUItLcP3N8A/HWOvAAaIHMIVIsF6+0=
    - secure: o7q6IlXMGTaiijVHuZGU1zgDT2QiyCKZCbdw5izxYmHCCx83Ea9gOnwjT2UIwkUR0fcAEtZhGa7i0qjvGJDDXFqwtOhDErvBvQPbYvGdsW/fOccsIKdtZpQ+rXzSgxzuv2FwAGm9HUnfUmNqliolZCZX9KI6+eK195srLPgb9aiB0AubvH1Xna9Y/xRfL4brXX37s+HRcXGa/CgCYVL9o9HmkYsDLPr2HPonT8CXfFtYCrepjhA1TKVWihU/qSFrCoQgrgnYHeoVSYseqhAvTdW8AhHCp4iELzoLcVpweko1Nlnjq4AwEgxiu4cy1CJbq5Yx1+QtUSmhB+ywpQh9BGFmlojDZJqFTQ3Myz0pVw9/ZaATgqJCOCW+o064XRdpLMnFRs3dGaR3J/TMb+GjzrNJ3AQ0RhvGX88Z5LO5RFckM5z0n9FSizkmEg6OZGS4hqQycn5mvsTHlSH+jC26maCy1iFHqK1LKdBkB0VKvLvFurHyWY3lK5NHRyu4BaxF0cVGUuiwxC9Xx7V+LWp35Fu+VII93lplap0Kas4ACOyNmHx6xvnXFthieFsNZEpSnO4kSpLYTOTY4uJiHkNuX0rin29h7fjt8lsS+Yc6slLIargo8R27/ohZR9U5mB4s4gIOuYVhohRF3eHig4I+EtkcL9A1FSEXAyMtxDBPy+w=
    - secure: qCxeTBmZmjSHlSg3RE6vpOSFXkLAhkiTrMV2Cq1tVF5fixE5OI+/j3TMLmM+1OB8Vs5mXb7lRYOrfkIfss2NqihDm3SBOFrDoY9xscnbKtlTVN1RQv5rxqkLdsHdiubHcqpmlyczB1/g8HU6D8g6ULnEuV08ArMzoO83h0QWP+LlAjtHvF/QVHWvRC0xXGgUJzz5rGCYoK4i497ugBJ7uc0cim0vdJgqwLtCYKlT/sACs/lNMe5t6vp8JhI5Bj0GD+QNiLGgA9MFZ5ERqQIzxSvK5SN4N/ZY+gjEU5UgGPZSgi3jGIZiHvat1L49dgr/565KuFWjK6WDVGM0h4neFgqyIe3l0yWSoblWM4peavIOXTlXCFGYg0l0IAMoRKnqthjNBLh7jHWllYp/hFdphG/VVH1ygxkn4L99xIyessaplZYxZHgE/DPVo2cYWseqSCsTJ0giuzsnw8CT0G8SOafBPAFkNHJRbAjZnqonsFottrkMgzI5++CIsXmmiTcmwWNqpCztBCIxB6bSvDo3UbwyDDlrEBZUvubCTZnORVaLxa6ba6KBYDyTrv8cK+itGJFKc5/byi6XEDt0y8UbVfrwRry1dNr1d5HHkmHREp3cVVUSwKr4RCSNnHnJ06q8aGu5NhWPVUCE8jjSpefAelr2zuHbHTe4ku9g0GTZsY4=
    - secure: FH+FuuLGUM4YxL+v7NHUw/aZ7bMu4z3FTsM7dBPSywZLBbDE4YVgRDeAlPQAi3AnYC0yJgUk5ilHdlCsFE932/jJcL/T3XUoh+XGPwYwIHWL9i43cACP7msgJhLvJNPkgALIMbg++50dD6yHOFu7TO9wSZ46vlkZBk0XRcwDUJgQL38MH10IqRj9eyDvCRIK4rJ9375lQNbuhMxPzJuvsfFWojFn11FEi8XMsVA6DH+v9n/RktC6WHkZl9TfK47OJjbDaJM6kWvPJTEx+QxFRXVicgQWNHTTUJ1JpCiNnfaTP3hCrLzCxGNZyxvey5dnBBDlK356ULh4cWa3f9HIzApn6QfkcpsB2H+kvEXjvQAX2tUiRFM6A7BlZOxTmv89c4zO5pfz5HPNs6m8otC52uaWSlyrbj6zg22gdyso6kTNQb2fjjnJxric5cM8+Az7vzW4TGI0BO+42mPCFXjPhi3a4ISBIXHaAUm9WCxNopqKaeqA2n56vb7LR7xmVSDhgNHrqCoPmJge2ap/HfvxIobHN3Ibf2W7M88J54VZD5Ce51JeAtEw/o3zswCt9HMUK1mIgjWRMrTFE8GoWagLdvAo3P7FvhJK0JwqO5PwTR19thysEZJg1iKarBWBliI8lOZHtgQzkSGA3dWfxNy1j7w6+40P1QC6dTWrjBzLBMA=
    - secure: wgNm6uTwmZZYhqRegdn4nMspji81tMqZTqSRI8Prx40V9kG82aXJM6bbBEnBaW4nyxQCgoKiUBmkUoZWhKwpzdw+A7Tb1fBRYdAk4X+aP5t/EbRGTg8bcKfJJTxoUA2Z+PDX6fG+73gTqokZYZXLYI5zakKxqJ566EPfRq2U6Au7ltp8qTRQKZsRaih9rPnhjtk5VFg2TEOj0g9ERgixpcSC59RT/fkoiWr+cATuWNmFR1fWCEBT0bSuDz5aVxIRswReiJ3K2dH0A+/ctV8qD4GtFxubriFiCDFAa1JBiZloGclfyr4T5jLQ1U6XDkfQm1lspjzdv7ti9m0LFlVxThhuCn9e4+sPHUzkiruxN39kjZcnj9i+dVdySpH3k61n6sGsq8WI813y9YmhOAuhB9yDl4uGD+sBb9+8PK/Vqvv40IgPct7l2I6gOm/zMg1KKsC5GuYIiXOdN9bbwJUcrn0zcS2M795NDSWwc1UAfUtaDRM7juT16HxKClac18eQxNl3NEQXkQWNVxO5YgnDmzvFB/a2Weceq+u8NpYlNpIQB5VQdxLPlHp85N3T+V+i/jMVWhPSL/BZ/NaLtQRNT+vc/XDxzGJnD4Bl8GiloSkEnDR47SHAyIm2ikC+Z9VuTqj5iuDrPAPV0bZRhHx8nSpjXGbJIQKXaw1Dty9Pd3c=
    - secure: UZME3Mn1fJzcLuUUui5Lk8/PWLDAFSE8BetGFhzD/tnty1NdKMBqWklKWK1kJYtzE2FpD520l6rcFxc9tcaFQtjBT0w+KFCtby2UtNlfZpQdFq+b/eBtJ1qLMYkkAN89iYnY7d/WIVUD73KAbTHXRnTwOCfURttP3KUYT30UX/XSeEwS5MCmxTpDYftWis0V1iAZ+//Fu8LRBwGSZHdUXYSUFdGIem2my0925YP7dfG1ngYlpxTZSaBDDgQEeK9ii7gwKvsoAl0QNeZyimtU3teBuad1tmP0NC+9x0ZMcrllTxzmtj8HitbHWKQpG8va2Ug1ZqusiMffsJ52dFS9EWRKHn1+b2quc9TNBFvU9HO84RUtFGEEMM9iREBFAaNYNoIfvZRRGmcExBFAIrjEoo/3kmTtlmZPHYntZ3/2msouD+lENZUNZyBYydCGAO1oH94gzMVLJ/Ne2pkrNzcFrzVg53sN1fb1zXQefL72GWAtEwRxevPD/h5RIe3+Rbzne8ek583alpaDQpuBGk9cYbfr7ELB3hJI85bShzJc7fPLj4dYRX4zCRiBCKeGNkEgCKSCiMFF1d4zqorgrmpR0ifLWfcZfFodtuS70l88t+HZ2loDoGzAqrSxdlBdlfRti4i44qGO5cOBLsfussUc0Z2MSFw+vmUe1bfRXknPAx4=
jobs:
  include:
    - cache:
        - node_modules
      install:
        - npm install -g serverless
        - travis_retry npm install
      script:
        - serverless deploy -s ${STAGE_NAME}
      name: Deploy base service
      if: type = push AND branch = develop
      env:
      - STAGE_NAME=dev
      - *4
    - <<: *DEPLOY_SERVICE_JOB
      name: Deploy league management API
      if: type = push AND branch = develop
      env:
        - STAGE_NAME=dev
        - SERVICE_PATH='services/leagueManagement'
        - *4

    # - cache: *1
    #   install: *2
    #   script: *3
    #   name: Deploy to the prod account
    #   if: type = push AND branch = master
    #   env:
    #   - STAGE_NAME=prod
    #   - *5