
service: march-madness-calcutta-api

custom:
  stage: ${opt:stage, self:provider.stage}
        
provider:
  name: aws
  runtime: nodejs16.x
  timeout: 15
  region: us-east-1
  stage: dev
  websocketsApiName: calcutta-websockets-api-${self:custom.stage}
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    NODE_ENV: ${self:custom.stage}
    APP_ENV: ${self:custom.stage}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST:
      Fn::GetAtt: [CalcuttaDBEC2, PublicIp]
    #   Fn::GetAtt: [ CalcuttaDB, Endpoint.Address ]
    DB_PORT: 1433
    #   Fn::GetAtt: [ CalcuttaDB, Endpoint.Port ]
  vpc:
    securityGroupIds:
      - Ref: LambdaSG
    subnetIds:
      - Ref: LambdaSubnet1
      - Ref: LambdaSubnet2
      - Ref: LambdaSubnet3


resources:
  - ${file(resources/vpc.yml)}
  - ${file(resources/subnets.yml)}
  - ${file(resources/route-tables.yml)}
  - ${file(resources/subnet-route-table-associations.yml)}
  - ${file(resources/internet-gateways.yml)}
  - ${file(resources/routes.yml)}
  - ${file(resources/security-groups.yml)}
  # - ${file(resources/rds.yml)}
  - ${file(resources/roles.yml)}
  - ${file(resources/conditions.yml)}
  - ${file(resources/ec2.yml)}
  - ${file(resources/instance-profile.yml)}