Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: calcutta-test-${self:custom.stage}
      UsernameAttributes:
        - email
      AliasAttributes:
        - email
        - preferred_username
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUpperCase: true
          RequireNumbers: true
          TemporaryPasswordValidityDays: 1
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: calcutta-test-${self:custom.stage}-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      RefreshTokenValidity: 30

  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 300
      IdentitySource: method.request.header.x-cognito-token
      Name: CognitoAuthorizer
      



Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool
    
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient