Resources:
  AuctionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: LastBidTimestamp
          AttributeType: S
        -
          AttributeName: Status
          AttributeType: S
        -
          AttributeName: CurrentItemId
          AttributeType: N
        -
          AttributeName: TeamLogoUrl
          AttributeType: S
        -
          AttributeName: ItemTypeId
          AttributeType: N
        -
          AttributeName: ItemName
          AttributeType: S
        -
          AttributeName: Seed
          AttributeType: N
        -
          AttributeName: DisplayName
          AttributeType: S
        -
          AttributeName: CurrentItemWinner
          AttributeType: N
        -
          AttributeName: Alias
          AttributeType: S
        -
          AttributeName: CurrentItemPrice
          AttributeType: N
        -
          AttributeName: RecordType
          AttributeType: S
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
        -
          AttributeName: LastBidTimestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25
      TableName: Auctions
      TableClass: STANDARD
      Tags:
        -
          Key: Description
          Value: 'Contains all auction bidding data'
      
  AuctionConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: UserId
          AttributeType: N
        -
          AttributeName: ConnectionId
          AttributeType: S
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: AuctionConnections
      TableClass: STANDARD
      Tags:
        -
          Key: Description
          Value: 'Contains the websocket connection Ids for each user'

  AuctionChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: Timestamp
          AttributeType: S
        -
          AttributeName: MessageId
          AttributeType: S
        -
          AttributeName: UserId
          AttributeType: N
        -
          AttributeName: Alias
          AttributeType: S
        -
          AttributeName: Content
          AttributeType: S
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
        -
          AttributeName: Timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: AuctionChat
      TableClass: STANDARD