Resources:
  AuctionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: LastBidTimestamp
          AttributeType: S
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
        -
          AttributeName: LastBidTimestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25
      TableName: Auctions
      TableClass: STANDARD
      Tags:
        -
          Key: Description
          Value: 'Contains all auction bidding data'
      
  AuctionConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: ConnectionId
          AttributeType: S
      KeySchema:
        -
          AttributeName: ConnectionId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: AuctionConnections
      TableClass: STANDARD
      Tags:
        -
          Key: Description
          Value: 'Contains the websocket connection Ids for each user'

  AuctionChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
        -
          AttributeName: Timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: AuctionChat
      TableClass: STANDARD

Outputs:
  AuctionConnectionTableArn:
    Description: 'ARN for AuctionConnectionTable'
    Value:
      Ref:
        Fn::GetAtt: [AuctionConnectionTable, Arn]
    Export:
      Name: calcutta-auction-connection-table-arn-${self:custom.stage}
  AuctionChatTableArn:
    Description: 'ARN for AuctionChatTable'
    Value:
      Ref:
        Fn::GetAtt: [AuctionChatTable, Arn]
    Export:
      Name: calcutta-auction-chat-table-arn-${self:custom.stage}
  AuctionTableArn:
    Description: 'ARN for AuctionTable'
    Value:
      Ref:
        Fn::GetAtt: [AuctionTable, Arn]
    Export:
      Name: calcutta-auction-table-arn-${self:custom.stage}