Resources:
  CalcuttaDBEC2:
    Type: AWS::EC2::Instance
    Condition: IsDev
    DependsOn:
      - CalcuttaGatewayAttachment
    Properties:
      AvailabilityZone: us-east-1f
      EbsOptimized: True
      ImageId: !If [IsDev, !Ref CalcuttaDBEC2_ImageId_DEV, !Ref CalcuttaDBEC2_ImageId_PROD]
      InstanceType: t3.micro
      IamInstanceProfile: !Ref CalcuttaIamInstanceProfile
      KeyName: calcutta-ec2
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp2
            DeleteOnTermination: True
      NetworkInterfaces:
        - AssociatePublicIpAddress: True
          DeviceIndex: '0'
          GroupSet:
            - Ref: DBSG
          SubnetId:
            Ref: NatSubnet3
      Tags:
        - Key: Name
          Value: 'Calcutta SQL Server'

Outputs:
  PublicDns:
    Description: Server public DNS
    Value: !GetAtt CalcuttaDBEC2.PublicDnsName
    Export:
      Name: calcutta-db-ec2-${self:custom.stage}-dns-address
  PublicIp:
    Description: Server public IP
    Value: !GetAtt CalcuttaDBEC2.PublicIp
    Export:
      Name: calcutta-db-ec2-${self:custom.stage}-address