Resources:
  CalcuttaRootVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1e
      Iops: 300
      Size: 10
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: 'Calcutta root volume'

  CalcuttaDataVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1e
      Iops: 300
      Size: 20
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: 'Calcutta data volume'

  CalcuttaDB_EC2:
    Type: AWS::EC2::Instance
    DependsOn:
      - CalcuttaGatewayAttachment
      - CalcuttaRootVolume
      - CalcuttaDataVolume
    Properties:
      EbsOptimized: True
      ImageId: ami-0c19f80dba70861db
      InstanceType: t3.micro
      KeyName: calcutta-ec2
      NetworkInterfaces:
        - AssociatePublicIpAddress: True
          DeviceIndex: '0'
          GroupSet:
            - Ref: DBSG
          SubnetId:
            Ref: NatSubnet2
      Volumes:
        - Device: /dev/sda1
          VolumeId:
            Ref: CalcuttaRootVolume
        - Device: xvdb
          VolumeId:
            Ref: CalcuttaDataVolume
      Tags:
        - Key: Name
          Value: 'Calcutta SQL Server'

  