Resources:
  LambdaRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: CalcuttaVPC
      Tags:
        - Key: Name
          Value: 'lambda-to-internet'
  
  NatRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: CalcuttaVPC
      Tags:
        - Key: Name
          Value: 'NAT GW'