Resources:
  LambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Lambda access to SQL Server'
      GroupName: Lambda_DMZ
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      VpcId:
        Ref: CalcuttaVPC

  DBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'SQL Server Security Group'
      GroupName: sql-server-calcutta
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          Description: 'Local Lambda Inbound'
          SourceSecurityGroupId:
            Ref: LambdaSG
          FromPort: 1433
          ToPort: 1433
        - IpProtocol: tcp
          Description: 'Cognito Lambda Inbound'
          SourceSecurityGroupId: ${env:AWS_COGNITO_LAMBDA_SG_ID}
          SourceSecurityGroupOwnerId: ${env:AWS_COGNITO_ACCOUNT_ID}
          FromPort: 1433
          ToPort: 1433
      VpcId:
        Ref: CalcuttaVPC

Outputs:
  LambdaSGId:
    Description: 'LambdaDMZ security group'
    Value:
      Ref: LambdaSG
    Export:
      Name: calcutta-lambdaSG-${self:custom.stage}