Resources:
  CalcuttaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: Calcutta-${self:custom.stage}

  CalcuttaPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerOwnerId: ${self:custom.secrets.AWS_COGNITO_ACCOUNT_ID}
      PeerRoleArn: arn:aws:iam::${self:custom.secrets.AWS_COGNITO_ACCOUNT_ID}:role/calcutta-${self:custom.stage}-peer-role
      PeerVpcId: ${self:custom.secrets.${self:custom.stage}.AWS_COGNITO_VPC_ID}
      VpcId:
        Ref: CalcuttaVPC
      Tags:
        - Key: Name
          Value: 'Cognito Peer'

Outputs:
  CalcuttaVPCId:
    Description: 'Calcutta VPC locical Id'
    Value:
      Ref: CalcuttaVPC
    Export:
      Name: calcutta-vpc-${self:custom.stage}