Resources:
  CalcuttaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        !If [IsProduction, 10.0.0.0/16, 10.2.0.0/16]
      EnableDnsHostnames: True
      EnableDnsSupport: True
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: calcutta-${self:custom.stage}

  CalcuttaPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerOwnerId: ${env:AWS_COGNITO_ACCOUNT_ID}
      PeerRoleArn: arn:aws:iam::${env:AWS_COGNITO_ACCOUNT_ID}:role/calcutta-${self:custom.stage}-peer-role
      PeerVpcId: ${env:AWS_COGNITO_VPC_ID}
      VpcId:
        Ref: CalcuttaVPC
      Tags:
        - Key: Name
          Value: 'Cognito Peer'

Outputs:
  CalcuttaVPCId:
    Description: 'Calcutta VPC locical Id'
    Value:
      Ref: CalcuttaVPC
    Export:
      Name: calcutta-vpc-${self:custom.stage}