Resources:
  AuctionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: LastBidTimestamp
          AttributeType: S
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
        -
          AttributeName: LastBidTimestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25
      TableName: ${self:custom.AUCTION_TABLE}
      TableClass: STANDARD
      Tags:
        -
          Key: Description
          Value: 'Contains all auction bidding data'
      
  AuctionConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: ConnectionId
          AttributeType: S
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
        -
          AttributeName: ConnectionId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: ${self:custom.CONNECTION_TABLE}
      TableClass: STANDARD
      Tags:
        -
          Key: Description
          Value: 'Contains the websocket connection Ids for each user'

  AuctionChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: LeagueId
          AttributeType: N
        -
          AttributeName: Timestamp
          AttributeType: N
      KeySchema:
        -
          AttributeName: LeagueId
          KeyType: HASH
        -
          AttributeName: Timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25
      TableName: ${self:custom.CHAT_TABLE}
      TableClass: STANDARD