Resources:
  AuctionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LeagueId
          AttributeType: N
      KeySchema:
        - AttributeName: LeagueId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.AUCTION_TABLE}
      TableClass: STANDARD
      Tags:
        - Key: Description
          Value: 'Contains all auction bidding data'

  BidHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LeagueId
          AttributeType: N
        - AttributeName: BidId
          AttributeType: N
      KeySchema:
        - AttributeName: LeagueId
          KeyType: HASH
        - AttributeName: BidId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.BID_HISTORY_TABLE}
      Tags:
        - Key: Description
          Value: 'Contains the bidding history for all auctions'
      
  AuctionConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ConnectionId
          AttributeType: S
        - AttributeName: LeagueId
          AttributeType: N
        - AttributeName: CognitoSub
          AttributeType: S
      KeySchema:
        -
          AttributeName: ConnectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.CONNECTION_TABLE}
      TableClass: STANDARD
      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.CONNECTION_TABLE}_LeagueId_CognitoSub
          KeySchema:
            - AttributeName: LeagueId
              KeyType: HASH
            - AttributeName: CognitoSub
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - Alias
              - UserId
      Tags:
        -
          Key: Description
          Value: 'Contains the websocket connection Ids for each user'

  AuctionChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LeagueId
          AttributeType: N
        - AttributeName: Timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: LeagueId
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.CHAT_TABLE}
      TableClass: STANDARD

  AuctionSettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LeagueId
          AttributeType: N
      KeySchema:
        - AttributeName: LeagueId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.AUCTION_SETTINGS_TABLE}
      TableClass: STANDARD

  AuctionLedgerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LeagueId
          AttributeType: N
        - AttributeName: LedgerId
          AttributeType: N
      KeySchema:
        - AttributeName: LeagueId
          KeyType: HASH
        - AttributeName: LedgerId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.AUCTION_LEDGER_TABLE}
      Tags:
        - Key: Description
          Value: 'Contains the sale/refund history for all auctions'

  LeagueMembershipTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LeagueId
          AttributeType: N
      KeySchema:
        - AttributeName: LeagueId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.LEAGUE_MEMBERSHIP_TABLE}
      TableClass: STANDARD