Resources:
  DynamoDBWebsocketRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: calcutta-${self:custom.stage}-dynamodb-websocket-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource:
                  - Fn::GetAtt: [AuctionConnectionTable, Arn]
                  - Fn::GetAtt: [AuctionChatTable, Arn]
                  - Fn::GetAtt: [AuctionTable, Arn]
                  - Fn::GetAtt: [BidHistoryTable, Arn]
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
              - Effect: Allow
                Resource:
                  - Fn::Sub:
                      - ${TableArn}/index/*
                      - TableArn:
                          Fn::GetAtt: [AuctionConnectionTable, Arn]
                Action:
                  - dynamodb:Query
                  - dynamodb:Scan
              - Effect: Allow
                Resource:
                  - arn:aws:execute-api:*:*:**/@connections/*
                Action:
                  - execute-api:ManageConnections
              - Effect: Allow
                Resource: '*'
                Action:
                  - lambda:InvokeFunction
              - Effect: Allow
                Resource:
                  - arn:aws:logs:us-east-1:*:*
                Action:
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:CreateLogStream