
service: calcutta-auction-service-v2

package:
  individually: true

plugins:
  - serverless-bundle

custom:
  stage: ${opt:stage, self:provider.stage}
  provider: ${file(../../common/config/provider.json)}
  AUCTION_TABLE: Auctions
  CONNECTION_TABLE: AuctionConnections
  CHAT_TABLE: AuctionChat

provider:
  name: aws
  runtime: nodejs12.x
  timeout: ${self:custom.provider.timeout}
  logRetentionInDays: ${self:custom.provider.logRetentionInDays}
  region: ${self:custom.provider.region}
  stage: ${self:custom.provider.stage}
  environment:
    APP_ENV: ${self:custom.stage} # used by the websocket verification function
    AUCTION_TABLE: ${self:custom.AUCTION_TABLE}
    CONNECTION_TABLE: ${self:custom.CONNECTION_TABLE}
    CHAT_TABLE: ${self:custom.CHAT_TABLE}
    WEBSOCKET_ENDPOINT:
      Fn::Join:
        - ''
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [AuctionConnectionTable, Arn]
        - Fn::GetAtt: [AuctionChatTable, Arn]
        - Fn::GetAtt: [AuctionTable, Arn]

functions:
  # websocket functions
  onConnect:
    handler: functions/websocket.onConnect
    # role:
    #   Fn::GetAtt: [DynamoDBWebsocketRole, Arn]
    events:
      - websocket:
          route: $connect
  onDisconnect:
    handler: functions/websocket.onDisconnect
    # role:
    #   Fn::GetAtt: [DynamoDBWebsocketRole, Arn]
    events:
      - websocket:
          route: $disconnect

resources:
  # - ${file(../../common/resources/api-gateway-authorizer.yml)}
  - ${file(resources/dynamodb.yml)}
  # - ${file(resources/roles.yml)}