
service: calcutta-auction-service-v2

package:
  individually: true

plugins:
  - serverless-bundle

custom:
  stage: ${opt:stage, self:provider.stage}
  provider: ${file(../../common/config/provider.json)}
  AUCTION_TABLE: Auctions
  CONNECTION_TABLE: AuctionConnections
  CHAT_TABLE: AuctionChat

provider:
  name: aws
  runtime: ${self:custom.provider.runtime}
  timeout: ${self:custom.provider.timeout}
  logRetentionInDays: ${self:custom.provider.logRetentionInDays}
  region: ${self:custom.provider.region}
  stage: ${self:custom.stage}
  environment:
    APP_ENV: ${self:custom.stage} # used by the websocket verification function
    AUCTION_TABLE: ${self:custom.AUCTION_TABLE}
    CONNECTION_TABLE: ${self:custom.CONNECTION_TABLE}
    CHAT_TABLE: ${self:custom.CHAT_TABLE}
    DB_NAME: ${self:custom.provider.env.DB_NAME}
    DB_USER: ${self:custom.provider.env.DB_USER}
    DB_PASSWORD: ${self:custom.provider.env.DB_PASSWORD}
    DB_HOST:
      Fn::ImportValue: ${self:custom.provider.env.DB_HOST}
    DB_PORT:
      Fn::ImportValue: ${self:custom.provider.env.DB_PORT}
    WEBSOCKET_ENDPOINT:
      Fn::Join:
        - ''
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:custom.stage}

functions:
  verifyUserLeague:
    handler: functions/verifyUserLeague.verifyUserLeague
    vpc:
      securityGroupIds:
        - Fn::ImportValue: ${self:custom.provider.vpc.securityGroupIds.LAMBDA_SG}
      subnetIds:
        - Fn::ImportValue: ${self:custom.provider.vpc.subnetIds.SUBNET1}
        - Fn::ImportValue: ${self:custom.provider.vpc.subnetIds.SUBNET2}
        - Fn::ImportValue: ${self:custom.provider.vpc.subnetIds.SUBNET3}

  # websocket functions
  onConnect:
    handler: functions/websocketConnection.onConnect
    role:
      Fn::GetAtt: [DynamoDBWebsocketRole, Arn]
    events:
      - websocket:
          route: $connect
  onDisconnect:
    handler: functions/websocketConnection.onDisconnect
    role:
      Fn::GetAtt: [DynamoDBWebsocketRole, Arn]
    events:
      - websocket:
          route: $disconnect
  handleMessage:
    handler: functions/websocketChat.sendChatMessage
    role:
      Fn::GetAtt: [DynamoDBWebsocketRole, Arn]
    events:
      - websocket:
          route: $default

resources:
  # - ${file(../../common/resources/api-gateway-authorizer.yml)}
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/roles.yml)}