
name: Stage

on:
  push:
    branches: develop

jobs:
  base_deploy:
    name: Deploy base service
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g serverless
      - run: npm install
      - run: serverless deploy -s $STAGE_NAME --verbose
  
  user_service:
    name: Deploy user service API
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/user
          serverless deploy -s $STAGE_NAME --verbose

  league_service:
    name: Deploy league service API
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/league
          serverless deploy -s $STAGE_NAME --verbose

# Completely replaced by auction-v2
  # auction_service:
  #   name: Deploy auction service API
  #   needs: base_deploy
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: use nodejs
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #     - run: npm install -g serverless
  #     - run: npm install
  #     - run: |
  #         cd services/auction
  #         serverless deploy -s $STAGE_NAME --verbose

  tournament_service:
    name: Deploy tournament service API
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/tournament
          serverless deploy -s $STAGE_NAME --verbose

  auction_service_v2:
    name: Deploy auction service API-v2
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/auction-new
          serverless deploy -s $STAGE_NAME --verbose
  
env:
  STAGE_NAME: dev
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_MASTER_USER: ${{ secrets.DB_MASTER_USER }}
  DB_MASTER_PASSWORD: ${{ secrets.DB_MASTER_PASSWORD }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  USER_POOL_ARN: ${{ secrets.USER_POOL_ARN_DEV }}
  AWS_COGNITO_VPC_ID: ${{ secrets.AWS_COGNITO_VPC_ID_DEV }}
  AWS_COGNITO_LAMBDA_SG_ID: ${{ secrets.AWS_COGNITO_LAMBDA_SG_ID_DEV }}
  AWS_COGNITO_ACCOUNT_ID: ${{ secrets.AWS_COGNITO_ACCOUNT_ID }}
  AWS_LINKED_SERVER_SG_ID: ${{ secrets.AWS_PROD_DB_SG_ID }}
  AWS_LINKED_SERVER_ACCOUNT_ID: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
  AWS_LINKED_SERVER_VPC_ID: ${{ secrets.AWS_PROD_VPC_ID }}