
name: Prod

on:
  push:
    branches: master

jobs:
  base_deploy:
    name: Deploy base service
    environment: prod
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g serverless
      - run: npm install
      - run: serverless deploy -s $STAGE_NAME

  user_service:
    name: Deploy user service API
    environment: prod
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/user
          npm install
          serverless deploy -s $STAGE_NAME

  league_service:
    name: Deploy league service API
    environment: prod
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/league
          npm install
          serverless deploy -s $STAGE_NAME

  tournament_service:
    name: Deploy tournament service API
    environment: prod
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/tournament
          npm install
          serverless deploy -s $STAGE_NAME

  auction_service_v2:
    name: Deploy auction service API-v2
    environment: prod
    needs: base_deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/auction-new
          npm install
          serverless deploy -s $STAGE_NAME
  
env:
  STAGE_NAME: prod
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  USER_POOL_ARN: ${{ secrets.USER_POOL_ARN }}
  USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
  USER_POOL_CLIENT_ID: ${{ secrets.USER_POOL_CLIENT_ID }}
  AWS_COGNITO_VPC_ID: ${{ secrets.AWS_COGNITO_VPC_ID }}
  AWS_COGNITO_LAMBDA_SG_ID: ${{ secrets.AWS_COGNITO_LAMBDA_SG_ID }}
  AWS_COGNITO_ACCOUNT_ID: ${{ secrets.AWS_COGNITO_ACCOUNT_ID }}